In [3]:
import numpy as np

m_sqr_arrA = np.array([[1, 2], [4, -1]])

print(m_sqr_arrA)

m_sqr_arrB = np.array([[2, -3], [-4, 1]])

print(m_sqr_arrB)

m_sqr_arrR = m_sqr_arrA-m_sqr_arrB

print(m_sqr_arrR)

[[ 1  2]
 [ 4 -1]]
[[ 2 -3]
 [-4  1]]
[[-1  5]
 [ 8 -2]]


In [4]:
import numpy as np

m_sqr_arr = np.array ([[-1, 0, 2],[0, 1, 0],[1, 2, -1]])

m_sqr_arrR = m_sqr_arr * m_sqr_arr

print(m_sqr_arrR)

[[1 0 4]
 [0 1 0]
 [1 4 1]]


In [5]:
m_sqr_arrA = np.array ([[3,5],[6,-1]])

m_sqr_arrB = np.array ([[2,1],[-3,2]])

m_sqr_arrR = m_sqr_arrA.dot(m_sqr_arrB)

print(m_sqr_arrR)

[[-9 13]
 [15  4]]


In [6]:
m_sqr_arr = np.array ([[2,3,4],[1,0,6],[7,8,9]])

print(m_sqr_arr)

np.linalg.det(m_sqr_arr)

[[2 3 4]
 [1 0 6]
 [7 8 9]]


35.00000000000001

In [7]:
m_sqr_arr = np.array ([[1,2,3,4],[-2,1,-4,3],[3,-4,-1,2],[4,3,-2,-1]])

print(m_sqr_arr)

np.linalg.det(m_sqr_arr)

[[ 1  2  3  4]
 [-2  1 -4  3]
 [ 3 -4 -1  2]
 [ 4  3 -2 -1]]


900.0000000000009